export const Rol = {
  ALUMNE: "ALUMNE",
  PROFESSOR: "PROFESSOR",
  CAP_DEPARTAMENT:"CAP_DEPARTAMENT",
  CAP_ESTUDIS: "CAP_ESTUDIS",
  DIRECTOR: "DIRECTOR",
  ADMINISTRADOR: "ADMINISTRADOR",
  ADMINISTRATIU: "ADMINISTRATIU",
  WEB: "WEB",
  ADMINISTRADOR_FCT: "ADMINISTRADOR_FCT",
  TUTOR_FCT: "TUTOR_FCT"
}
